### ISSUE TITLE
node-gyp build error

### ISSUE THREAD

**Issue by woqidaideshi** [Holusion/node-x-screen#1]
I git clone the resource, but after I 'node-gyp configure --target=**_',  I node-gyp build it. Then I got an error :
make: Entering directory `/home/yff/node_modules/node-x-screen/build'
  CXX(target) Release/obj.target/xscreen/src/nox.o
../src/nox.cc:9:20: error: ‘FunctionCallbackInfo’ does not name a type
 void getSize(const FunctionCallbackInfo<Value>& args) {
                    ^
../src/nox.cc:9:20: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/nox.cc:9:40: error: expected ‘,’ or ‘...’ before ‘<’ token
 void getSize(const FunctionCallbackInfo<Value>& args) {
                                        ^
../src/nox.cc: In function ‘void getSize(int)’:
../src/nox.cc:11:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate_&)’
   HandleScope scope(isolate);
                            ^
../src/nox.cc:11:28: note: candidates are:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../src/nox.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
   HandleScope(const HandleScope&);
   ^
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate_’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
   HandleScope();
   ^
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/nox.cc:12:43: error: no matching function for call to ‘v8::Object::New(v8::Isolate_&)’
   Local<Object> size = Object::New(isolate);
                                           ^
../src/nox.cc:12:43: note: candidate is:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../src/nox.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h:1724:33: note: static v8::Localv8::Object v8::Object::New()
   V8EXPORT static Local<Object> New();
                                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1724:33: note:   candidate expects 0 arguments, 1 provided
../src/nox.cc:13:13: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
   size->Set(String::NewFromUtf8(isolate,"width"),Number::New(isolate,1280));
             ^
../src/nox.cc:13:74: error: no matching function for call to ‘v8::Number::New(v8::Isolate_&, int)’
   size->Set(String::NewFromUtf8(isolate,"width"),Number::New(isolate,1280));
                                                                          ^
../src/nox.cc:13:74: note: candidate is:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../src/nox.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note: static v8::Localv8::Number v8::Number::New(double)
   V8EXPORT static Local<Number> New(double value);
                                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../src/nox.cc:14:13: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
   size->Set(String::NewFromUtf8(isolate,"height"),Number::New(isolate,1024));
             ^
../src/nox.cc:14:75: error: no matching function for call to ‘v8::Number::New(v8::Isolate_&, int)’
   size->Set(String::NewFromUtf8(isolate,"height"),Number::New(isolate,1024));
                                                                           ^
../src/nox.cc:14:75: note: candidate is:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../src/nox.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note: static v8::Localv8::Number v8::Number::New(double)
   V8EXPORT static Local<Number> New(double value);
                                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../src/nox.cc:15:3: error: ‘args’ was not declared in this scope
   args.GetReturnValue().Set(size);
   ^
../src/nox.cc: In function ‘void init(v8::Handlev8::Object)’:
../src/nox.cc:20:45: error: no matching function for call to ‘SetMethod(v8::Handlev8::Object&, const char [8], void (&)(int))’
   NODE_SET_METHOD(exports, "getSize",getSize);
                                             ^
../src/nox.cc:20:45: note: candidate is:
In file included from ../src/nox.cc:1:0:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char_, v8::InvocationCallback)
 void SetMethod(target_t obj, const char_ name,
      ^
/usr/include/nodejs/src/node.h:112:6: note:   template argument deduction/substitution failed:
../src/nox.cc:20:45: note:   cannot convert ‘getSize’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handlev8::Value (_)(const v8::Arguments&)}’
   NODE_SET_METHOD(exports, "getSize",getSize);
                                             ^
make: *_\* [Release/obj.target/xscreen/src/nox.o] Error 1
make: Leaving directory `/home/yff/node_modules/node-x-screen/build'
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-24-generic

How can I fix it?  thanks...

**Comment by sdumetz** [comment]
If it's trying to compile on nox.c that's because you don't have X11 headers installed. this is just a dummy file I made to make my CI happy. The proper module needs those headers to work.

Other problem theremight be is depending on tyour node version. Are you using node >=0.11 ?
